### ISSUE TITLE
Add supports for excluding files using a .ignore file or anything like that

### ISSUE THREAD

**Issue by ghost** [wlixcc/SFTP-Deploy-Action#13]
I need to ignore some files like
./vendor
.README..nd

**Comment by dstojchevski** [comment]
Is it possible?

**Comment by eruhtech** [comment]
Yes, is it possible or not?

**Comment by wlixcc** [comment]
The feature for excluding specific files and directories during deployment has been successfully implemented in version **v1.2.5**. 🎉

### ✅ **How to use `rsyncArgs` for excluding files:**

You can now use the `rsyncArgs` input to specify exclusion patterns. Here's an example:

```yaml
- name: Deploy with rsync exclude
  uses: wlixcc/SFTP-Deploy-Action@v1.2.5
  with:
    username: 'root'
    server: 'your.server.ip'
    ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
    local_path: './'
    remote_path: '/var/www/app'
    rsyncArgs: '--exclude=node_modules --exclude=.git --exclude=*.log'
    sftpArgs: '-o ConnectTimeout=5'
```

📚 Explanation:
--exclude=node_modules excludes the node_modules folder.
--exclude=.git excludes the .git folder.
--exclude=*.log excludes all .log files.
For more advanced usage, you can see rsync documentation
