### ISSUE TITLE
Exclude files or folder directory?

### ISSUE THREAD

**Issue by dstojchevski** [wlixcc/SFTP-Deploy-Action#29]
Is is possible to exclude any files or folders when executing the script?

**Comment by flavio89** [comment]
I'm also having the same problem.
Removing a local file does not remove it on the remote.

**Comment by edward795** [comment]
Ya a much needed feature to exclude files/folders..??

**Comment by VictorioBerra** [comment]
I would like this too.

In the meantime, I use the following:

```yaml
...

      - uses: actions/checkout@master

      - name: Copy to staging directory for deployment
        run: |
          mkdir deploy
          rsync -av --progress . deploy --exclude .git --exclude deploy --exclude .gitignore --exclude .github

      - name: 'Remote: deploy'
        uses: wlixcc/SFTP-Deploy-Action@v1.2.3
        with:
          username: ${{ secrets.USERNAME }}
          server: ${{ secrets.HOST }}
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }} 
          local_path: './deploy'
          remote_path: '/home/myuser/myapp'
```

**Comment by zvassos** [comment]
Still nothing? How do you guys manage this thing?

**Comment by wlixcc** [comment]
The feature for excluding specific files and directories during deployment has been successfully implemented in version **v1.2.5**. 🎉

### ✅ **How to use `rsyncArgs` for excluding files:**

You can now use the `rsyncArgs` input to specify exclusion patterns. Here's an example:

```yaml
- name: Deploy with rsync exclude
  uses: wlixcc/SFTP-Deploy-Action@v1.2.5
  with:
    username: 'root'
    server: 'your.server.ip'
    ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
    local_path: './'
    remote_path: '/var/www/app'
    rsyncArgs: '--exclude=node_modules --exclude=.git --exclude=*.log'
    sftpArgs: '-o ConnectTimeout=5'
```

📚 Explanation:
--exclude=node_modules excludes the node_modules folder.
--exclude=.git excludes the .git folder.
--exclude=*.log excludes all .log files.
For more advanced usage, you can see rsync documentation
