### ISSUE TITLE
Github Actions to use SFTP to send a file to Sourceforge

### ISSUE THREAD

**Issue by AndreMikulec** [wlixcc/SFTP-Deploy-Action#35]
Thanks,

No error here.  Many thanks to the author.

For anyone who cares, this works well in sending a file to Sourceforge.
I used the `password` method.

Setup:
https://github.com/AndreMikulec/testGithubActions/blob/98f547953df269946eaf0caddcd719ff6e45426f/.github/workflows/Test_SFTP_Deploy_Files.yml
```
- name: Deploy Files
  uses: wlixcc/SFTP-Deploy-Action@v1.2.4
  with:
    username: 'andremikulec,andremikulec.u'
    server: 'frs.sourceforge.net'
    port: 22
    local_path: './readme_Test_SFTP_Deploy_Files.md'
    remote_path: '/home/frs/project/andremikulec'
    sftp_only: true
    password: ${{ env.SF_ANDREMIKULEC_PWD }}

```

Run result:
https://github.com/AndreMikulec/testGithubActions/runs/7377842142?check_suite_focus=true#step:6:23

File is transferred:
https://sourceforge.net/projects/andremikulec/files/

# Extra info

This sftp target is the same as what I use on Appveyor.

https://github.com/AndreMikulec/r-base/blob/40dda14d5957ea5f2190825d70df3bee23e1e966/appveyor.yml#L85

When I try(test) manually from the command line, this works fine, too.

Cygwin:
```
AnonymousUser@ANONYMOUST ~
$ sftp andremikulec,andremikulec.u@frs.sourceforge.net
(andremikulec,andremikulec.u@frs.sourceforge.net) Password:
Connected to frs.sourceforge.net.
sftp> pwd
Remote working directory: /
sftp> cd /home/frs/project/andremikulec
sftp> pwd
Remote working directory: /home/pfs/project/andremikulec
sftp>
```

PSFTP (from PuTTy tools)
```
psftp: no hostname specified; use "open host.name" to connect
psftp> open frs.sourceforge.net
login as: andremikulec,andremikulec.u
Keyboard-interactive authentication prompts from server:
| Password:
End of keyboard-interactive prompts from server
Remote working directory is /
psftp> cd /home/frs/project/andremikulec
psftp> pwd
Remote directory is /home/pfs/project/andremikulec
psftp>
```

Andre Mikulec
