### ISSUE TITLE
What should be used for 'remote_path' to reference current remote directory?

### ISSUE THREAD

**Issue by fhg-isi** [wlixcc/SFTP-Deploy-Action#56]
What should be used for `remote_path `to reference current/working directory on remote server without need for an absolute path?

Following variants did not work:

```
''
'.'
'./'
'/'
```

**Comment by fhg-isi** [comment]
The SFTP-Deploy-Action currently does not seem to support relative paths. 
As a workaround, in order to find out my absolute path, I created some index.php file with following content:
<?php echo __FILE__; ?>
and opend that file in a browser. The result was something like

'/usr/www/users/{foo_user}/html/{qux_workspace}/'

**Comment by fhg-isi** [comment]
Found an alternative action that works for me:

```
   -name: deploy
    uses: pressidium/lftp-mirror-action@v1
    with:
    host: ${{ secrets.SFTP_URL }}
    port: ${{ secrets.SFTP_PORT }}
    user: ${{ secrets.SFTP_USER }}
    pass: ${{ secrets.SFTP_PASSWORD }}
    localDir: './toupload'
    remoteDir: '.'
    reverse: true
```
